# Utiliser une image de base Node.js
FROM node:20-alpine

# Créer un répertoire de travail
WORKDIR /usr/src/app

# Copier package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
ARG NODE_ENV
RUN if [ "$NODE_ENV" = "production" ]; then \
    npm ci --only=production; \
    else \
    npm install; \
    fi

# Copier le reste de l'application
COPY . .

EXPOSE 3000

# Lire la méthode de démarrage et le port à partir de .env
CMD ["sh", "-c", "npm run dev"]
